name: "Terraform setup and apply"
description: "Applys a terraform plan file from an artifact"
inputs:
  terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
  terraform_user_ocid:
    description: 'Oracle Cloud user OCID'
    required: true
  terraform_tenant_ocid:
    description: 'Oracle Cloud Tenant OCID'
    required: true
  terraform_key_privatekey:
    description: 'Oracle Cloud API private key'
    required: true
  terraform_key_fingerprint:
    description: 'Oracle Cloud API key fingerprint'
    required: true
  tfcloud_api_token:
    description: 'TF Cloud API token for remote statefile'
    required: true
  terraform_cloudflare_api_token:
    description: 'CloudFlare API token'
    required: true
  terraform_compartment_ocid:
    description: 'Oracle Compartment OCID'
    required: true
  terraform_version:
    description: 'Terraform Version'
    required: true
    default: 1.10.5
  terraform_cloudflare_zone_id:
    description: 'CloudFlare Zone ID'
    required: true
  github_token:
    description: 'GitHub token for auth'
    required: true
  pr_id:
    description: 'Pull request ID'
    required: true

runs:
  using: "composite"
  steps:
    # Dependabot has no access to secrets and tf init with remote backend will fail
    - name: Stop if Dependabot branch
      id: check_dependabot
      shell: bash
      run: |
        if [[ "${{ github.ref }}" == *"dependabot/github_actions"* ]]; then
          echo "Dependabot branch detected, stopping workflow."
          exit 1
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false
        cli_config_credentials_token: ${{ inputs.tfcloud_api_token }}

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        terraform init

    - name: Download Plan
      id: download-plan
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{ inputs.github_token }}
        workflow: plan.yml
        pr: ${{ inputs.pr_id }}
        name: ${{ inputs.pr_id }}-tf-plan
        path: ${{ inputs.terraform_directory }}

    - name: Terraform Apply
      id: apply
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        echo 'apply<<EOF' >> $GITHUB_OUTPUT
        terraform apply -input=false -no-color tfplan >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      env:
        TF_VAR_USER_OCID: ${{ inputs.terraform_user_ocid }}
        TF_VAR_TENANCY_OCID: ${{ inputs.terraform_tenant_ocid }}
        TF_VAR_PRIVATE_KEY: ${{ inputs.terraform_key_privatekey }}
        TF_VAR_FINGERPRINT: ${{ inputs.terraform_key_fingerprint }}
        TF_VAR_COMPARTMENT_OCID: ${{ inputs.terraform_compartment_ocid }}
        TF_VAR_CLOUDFLARE_API_TOKEN: ${{ inputs.terraform_cloudflare_api_token }}
        TF_VAR_CLOUDFLARE_ZONE_ID: ${{ inputs.terraform_cloudflare_zone_id }}

    - name: Comment Apply
      id: comment-apply
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ inputs.pr_id }}
        body: |
          Terraform Apply:

          ```
          ${{ steps.apply.outputs.apply }}
          ```