name: Terraform Destroy

on: workflow_dispatch

env:
  TERRAFORM_VERSION: "1.4.6"
  TF_IN_AUTOMATION: "True"

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Destroy
        uses: ./.github/destroy
        with:
          terraform_directory: "terraform"
          terraform_user_ocid: ${{ secrets.TF_USER_OCID }}
          terraform_tenant_ocid: ${{ secrets.TF_TENANCY_OCID }}
          terraform_key_privatekey: ${{ secrets.TF_PRIVATE_KEY }}
          terraform_key_fingerprint: ${{ secrets.TF_FINGERPRINT }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          tfcloud_api_token: ${{ secrets.TF_API_TOKEN }}
          terraform_compartment_ocid: ${{ secrets.TF_COMPARTMENT_OCID }}
          terraform_cloudflare_api_token: ${{ secrets.TF_CLOUDFLARE_API_TOKEN }}
          github_token: ${{ secrets.GH_TOKEN }}
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
